version: '3.8'

services:
  api-staging:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nx-api-staging
    network_mode: "host"
    env_file:
      - apps/api/.env.staging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3012/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web-staging:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: nx-web-staging
    network_mode: "host"
    env_file:
      - apps/web/.env.staging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3022"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Using host network mode - no need for external network

