version: '3.8'

services:
  api-prod:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nx-api-prod
    network_mode: "host"
    env_file:
      - apps/api/.env.prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3013/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web-prod:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: nx-web-prod
    network_mode: "host"
    env_file:
      - apps/web/.env.prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3023"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Using host network mode - no need for external network

