version: '3.8'

services:
  api-qa:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nx-api-qa
    ports:
      - "3011:3001"
    environment:
      - NODE_ENV=qa
      - PORT=3001
    env_file:
      - apps/api/.env.qa
    restart: unless-stopped
    networks:
      - npm_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web-qa:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: nx-web-qa
    ports:
      - "3021:3008"
    environment:
      - NODE_ENV=qa
      - API_URL=http://nx-api-qa:3001
      - PORT=3008
    depends_on:
      - api-qa
    restart: unless-stopped
    networks:
      - npm_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3008"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  npm_network:
    external: true

