version: '3.8'

services:
  api-staging:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nx-api-staging
    ports:
      - "3012:3002"
    environment:
      - NODE_ENV=staging
      - PORT=3002
    env_file:
      - apps/api/.env.staging
    restart: unless-stopped
    networks:
      - npm_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web-staging:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: nx-web-staging
    ports:
      - "3022:3008"
    environment:
      - NODE_ENV=staging
      - API_URL=http://nx-api-staging:3002
      - PORT=3008
    depends_on:
      - api-staging
    restart: unless-stopped
    networks:
      - npm_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3008"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  npm_network:
    external: true

