version: '3.8'

services:
  api-prod:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nx-api-prod
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - PORT=3009
    env_file:
      - apps/api/.env.prod
    restart: unless-stopped
    networks:
      - npm_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3009/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web-prod:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: nx-web-prod
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - API_URL=http://nx-api-prod:3009
      - PORT=3008
    depends_on:
      - api-prod
    restart: unless-stopped
    networks:
      - npm_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3008"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  npm_network:
    external: true

