version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nx-api
    expose:
      - "3009"
    environment:
      - NODE_ENV=production
      - PORT=3009
    restart: unless-stopped
    networks:
      - npm_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3009/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: nx-web
    expose:
      - "3008"
    environment:
      - NODE_ENV=production
      - API_URL=http://nx-api:3009
      - PORT=3008
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - npm_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3008"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  npm_network:
    external: true

