version: '3.8'

services:
  api-qa:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nx-api-qa
    network_mode: "host"
    env_file:
      - apps/api/.env.qa
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3011/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web-qa:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: nx-web-qa
    network_mode: "host"
    env_file:
      - apps/web/.env.qa
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3021"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Using host network mode - no need for external network

