name: CD - Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub (Optional)
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        continue-on-error: true
      
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/api/Dockerfile
          push: false
          tags: |
            nx-api:latest
            nx-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/web/Dockerfile
          push: false
          tags: |
            nx-web:latest
            nx-web:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            set -e
            
            # Check if directory exists
            if [ ! -d "/opt/nx-mono-repo" ]; then
              echo "Error: /opt/nx-mono-repo does not exist!"
              echo "Please run the VPS setup script first."
              echo "See VPS_INITIAL_SETUP.md for instructions."
              exit 1
            fi
            
            # Navigate to deployment directory
            cd /opt/nx-mono-repo
            
            # Pull latest changes
            echo "Pulling latest changes..."
            git pull origin main
            
            # Create network if it doesn't exist
            if ! docker network ls | grep -q npm_network; then
              echo "Creating npm_network..."
              docker network create npm_network
            fi
            
            # Stop and remove containers
            echo "Stopping containers..."
            docker-compose down || true
            
            # Build images
            echo "Building images..."
            docker-compose build --no-cache
            
            # Start containers
            echo "Starting containers..."
            docker-compose up -d
            
            # Wait for containers to start
            sleep 10
            
            # Check container status
            echo "Checking container status..."
            docker-compose ps
            
            # Clean up
            echo "Cleaning up unused Docker resources..."
            docker system prune -f
      
      - name: Health Check
        run: |
          sleep 30
          curl -f ${{ secrets.VPS_HOST }}/health || exit 1
        continue-on-error: true
      
      - name: Notify deployment status
        if: always()
        run: |
          echo "Deployment completed with status: ${{ job.status }}"

